// ---------- SÖZÜM SÖZ: core app logic ----------

(function () {
  "use strict";

  var STORE_KEY = "sozumsoz-v1";
  var AI_STAMP = "This content was generated by an artificial intelligence (AI) model. AI can make mistakes; this output is for awareness purposes only and is not a medical diagnosis or treatment recommendation. For important decisions, it is recommended to consult a professional (doctor, psychologist).";

  // Fall back to a monogram if the logo image fails to load (practically not triggered with inline SVG)
  window.__ssIconFallback = function (img) {
    if (!img) return;
    var mono = document.createElement("span");
    mono.className = "app-icon-fall";
    mono.textContent = img.getAttribute("data-mono") || "";
    try { img.parentNode.replaceChild(mono, img); } catch (e) { img.remove(); }
  };

  var noStorage = false;
  try { localStorage.setItem("__sozumsoz_probe", "1"); localStorage.removeItem("__sozumsoz_probe"); }
  catch (e) { noStorage = true; }

  function getStore() {
    return noStorage ? null : localStorage;
  }
  var HOP_WINDOW_MS = 90 * 1000;
  var REWARD_KEPT = 3;
  var PENALTY = -5;
  var BREAK_SECONDS = 20;

  function todayKey() {
    var d = new Date();
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }

  function nowHM(ts) {
    return new Date(ts || Date.now()).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
  }

  function appById(id) {
    return APPS.filter(function (a) { return a.id === id; })[0];
  }

  // ---------- state ----------
  var state = {
    points: 0,
    streak: 0,
    bestStreak: 0,
    kept: 0,
    brokenExceed: 0,
    brokenHop: 0,
    milestones: [],
    history: [],
    today: todayKey(),
    todayKept: 0,
    challengeClaimed: false,
    rewardOrders: [],
    breaksTaken: 0,
    lotteryEnteredMonth: null,
    lastClose: null,
    feed: [],
    ai: { live: false, provider: "openai", baseUrl: "https://api.openai.com/v1", model: "gpt-4o-mini", apiKey: "" },
    speedFast: true,
    seenIntro: false,
    weeklyDemo: null,
    chatHistory: [],
    breaksLog: [],
    consent: false,
    challenges: { week: null, joined: [], claimed: [] }
  };

  function save() {
    try { localStorage.setItem(STORE_KEY, JSON.stringify(state)); } catch (e) { /* noop */ }
  }

  function load() {
    try {
      var raw = localStorage.getItem(STORE_KEY);
      if (raw) {
        var s = JSON.parse(raw);
        Object.keys(state).forEach(function (k) {
          if (typeof s[k] !== "undefined") state[k] = s[k];
        });
      }
    } catch (e) { /* noop */ }
    if (!state.ai.provider) state.ai.provider = "openai";
    if (!state.challenges) state.challenges = { week: null, joined: [], claimed: [] };
    if (!state.breaksLog) state.breaksLog = [];
    var tk = todayKey();
    if (state.today !== tk) {
      state.today = tk;
      state.todayKept = 0;
      state.challengeClaimed = false;
    }
  }

  // ---------- helpers ----------
  function $(id) { return document.getElementById(id); }

  var session = null;
  var tickerId = null;
  var bgMode = "session";
  var appBooted = false;

  function fmtDelta(delta) { return (delta >= 0 ? "+" : "") + delta; }

  function esc(str) {
    return String(str)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }

  // ---------- typewriter text effect ----------
  function typeText(container, text, done) {
    if (window.__SS_INSTANT) {
      container.textContent = text;
      if (done) done();
      return;
    }
    var i = 0, n = text.length;
    if (!n) { if (done) done(); return; }
    (function tick() {
      i += 1;
      container.textContent = text.slice(0, i);
      if (i < n) { setTimeout(tick, 1); }
      else if (done) { done(); }
    })();
  }

  // ---------- floating points effect ----------
  function floatPoints(delta) {
    try {
      var anchor = $("hPoints");
      if (!anchor) return;
      var el = document.createElement("span");
      el.className = "float-pts";
      el.textContent = (delta > 0 ? "+" : "") + delta;
      anchor.parentNode.appendChild(el);
      var r = anchor.getBoundingClientRect();
      var rr = anchor.parentNode.getBoundingClientRect();
      el.style.left = (r.left - rr.left + r.width / 2 - 15) + "px";
      el.style.top = (r.top - rr.top) + "px";
      setTimeout(function () { if (el.parentNode) el.parentNode.removeChild(el); }, 1100);
    } catch (e) { /* cosmetic; process must not be affected on error */ }
  }

  // ---------- notifications ----------
  var NOTIF_ICONS = { info: "💬", warn: "⏰", danger: "🚫", good: "🎉", bg: "📲" };
  if (window.__SS_INSTANT) { window.__ss_notify = function (t, b, k, a) { return notify(t, b, k, a); }; }
  function notify(title, body, kind, actions) {
    var stack = $("notifStack");
    if (!stack) return null;
    var key = title + "|" + body;
    for (var i = stack.children.length - 1; i >= 0; i--) {
      if (stack.children[i].getAttribute("data-key") === key) stack.removeChild(stack.children[i]);
    }
    while (stack.querySelectorAll(".notif:not(.fading)").length >= 3) {
      var oldest = stack.querySelector(".notif:not(.fading)");
      if (!oldest) break;
      stack.removeChild(oldest);
    }
    var el = document.createElement("div");
    el.className = "notif k-" + (kind || "info");
    el.setAttribute("data-key", key);
    el.innerHTML =
      "<div class='n-icon'>" + (NOTIF_ICONS[kind] || "💬") + "</div>" +
      "<div class='n-box'><div class='n-title'>" + title + "</div><div class='n-body'>" + body + "</div></div>";
    if (actions && actions.length) {
      var row = document.createElement("div");
      row.className = "notif-actions";
      actions.forEach(function (a) {
        var b = document.createElement("button");
        b.className = "btn " + (a.cls || "btn-ghost");
        b.textContent = a.label;
        b.addEventListener("click", function () { a.onClick(); });
        row.appendChild(b);
      });
      el.appendChild(row);
    }
    stack.appendChild(el);
    if (state && state.feed) pushFeed(title + " - " + body);
    var life = actions && actions.length ? 30000 : 4500;
    setTimeout(function () {
      el.classList.add("fading");
      setTimeout(function () { if (el.parentNode) el.parentNode.removeChild(el); }, 520);
    }, life);
    return el;
  }
  function dismissNotif(el) {
    if (!el) return;
    el.classList.add("fading");
    setTimeout(function () { if (el.parentNode) el.parentNode.removeChild(el); }, 300);
  }

  // ---------- feed ----------
  function pushFeed(text) {
    state.feed.unshift({ text: text, ts: Date.now() });
    state.feed = state.feed.slice(0, 30);
    save();
    renderFeed();
  }

  function feedEmoji(text) {
    if (/break/i.test(text)) return "☕";
    if (/draw|lottery/i.test(text)) return "🎟️";
    if (/order|reward/i.test(text)) return "🏆";
    if (/streak/i.test(text)) return "⚡";
    if (/kept|completed|earned|won/i.test(text)) return "🎉";
    if (/exceed|overshoot|went/i.test(text)) return "⏰";
    if (/hop|switch/i.test(text)) return "🚫";
    if (/point/i.test(text)) return "🌟";
    return "📲";
  }

  function renderFeed() {
    var el = $("phoneFeed");
    if (!el) return;
    if (!state.feed.length) { el.innerHTML = "No activity yet."; el.className = "feed muted"; return; }
    el.className = "feed";
    el.innerHTML = state.feed.slice(0, 10).map(function (f) {
      return "<div class='feed-item'><span class='feed-emoji'>" + feedEmoji(f.text) + "</span>" +
        "<span class='feed-text'>" + f.text + "</span>" +
        "<span class='feed-time'>" + nowHM(f.ts) + "</span></div>";
    }).join("");
  }

  // ---------- tab routing ----------
  function setTab(name) {
    document.querySelectorAll(".tab").forEach(function (t) {
      t.classList.toggle("active", t.getAttribute("data-tab") === name);
    });
    document.querySelectorAll(".tabpanel").forEach(function (p) {
      p.classList.toggle("active", p.id === "tab-" + name);
    });
    if (name === "stats") renderStats();
    if (name === "charts") renderCharts();
    if (name === "challenges") renderChallenges();
    if (name === "rewards") renderRewards();
    if (name === "draw") renderDraw();
    if (name === "ai") renderAIStatus();
  }

  document.querySelectorAll(".tab").forEach(function (t) {
    t.addEventListener("click", function () { setTab(t.getAttribute("data-tab")); });
  });

  // ---------- header ----------
  var WEEKLY_MOODS = {
    good: { emoji: "😀", label: "good" },
    mid: { emoji: "😐", label: "average" },
    bad: { emoji: "🙁", label: "bad" }
  };

  function weeklyMoodKey() {
    var key = state.weeklyDemo;
    if (!key) {
      var since = Date.now() - 7 * 86400000;
      var kept = 0, broken = 0;
      state.history.forEach(function (h) {
        if (h.ts >= since) {
          if (h.result === "kept") kept++; else broken++;
        }
      });
      if (kept === 0 && broken === 0) key = "mid";
      else if (kept >= 3 && (kept / (kept + broken)) >= 0.8) key = "good";
      else if (kept >= 2 && (kept / (kept + broken)) >= 0.5) key = "mid";
      else key = "bad";
    }
    return key;
  }

  function weeklyMood() {
    return WEEKLY_MOODS[weeklyMoodKey()] || WEEKLY_MOODS.mid;
  }

  function moodFaceSVG(key) {
    var paths = {
      good: "<circle cx='9' cy='9.4' r='1.15'/><circle cx='15' cy='9.4' r='1.15'/><path d='M8 13.8c1.1 1.25 2.6 1.9 4 1.9s2.9-.65 4-1.9'/>",
      mid: "<circle cx='9' cy='9.4' r='1.15'/><circle cx='15' cy='9.4' r='1.15'/><path d='M8.6 15h6.8'/>",
      bad: "<path d='M8.1 8.4c.35-.95 1-1.5 1.7-1.5s1.35.55 1.7 1.5'/><path d='M12.5 8.4c.35-.95 1-1.5 1.7-1.5s1.35.55 1.7 1.5'/><path d='M8 16.6c1.1-1.3 2.6-2 4-2s2.9.7 4 2'/>"
    };
    return "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' stroke-linejoin='round' aria-hidden='true'>" +
      (paths[key] || paths.mid) + "</svg>";
  }

  function updatePhoneMood() {
    var el = $("phoneMood");
    if (!el) return;
    var okno = weeklyMoodKey();
    el.className = "s-status-mood mood-" + okno;
    el.innerHTML = moodFaceSVG(okno);
  }

  function updateMoodUI() {
    var pill = $("hMood");
    if (pill) pill.textContent = weeklyMood().emoji;
    updatePhoneMood();
    updateBgNotif();
  }

  function updateBgNotif() {
    var e = $("bgNotif");
    if (!e) return;
    var mood = weeklyMood();
    if (bgMode === "soz") {
      e.innerHTML =
        "<div class='n-icon'>📊</div>" +
        "<div class='n-box'><div class='n-title'>SÖZÜM SÖZ open " + mood.emoji + "</div>" +
        "<div class='n-body'>This week: " + mood.label + " performance · summary inside the app.</div></div>";
    } else {
      e.innerHTML =
        "<div class='n-icon'>🛡️</div>" +
        "<div class='n-box'><div class='n-title'>SÖZÜM SÖZ running in the background " + mood.emoji + "</div>" +
        "<div class='n-body'>Promise tracking active · " + nowHM() + "</div></div>";
    }
  }

  function showBgNotif(mode) {
    bgMode = mode || "session";
    if (!$("bgNotif")) {
      var el = document.createElement("div");
      el.id = "bgNotif";
      el.className = "notif k-bg";
      $("notifStack").appendChild(el);
    }
    updateBgNotif();
  }

  function hideBgNotif() {
    var e = $("bgNotif");
    if (e && e.parentNode) e.parentNode.removeChild(e);
  }

  function renderHeader() {
    $("hPoints").textContent = state.points;
    $("hStreak").textContent = state.streak;
    updateMoodUI();
  }

  // ---------- PHONE: home screen ----------
  function renderHome() {
    var screen = $("phoneScreen");
    var now = new Date();
    var hour = now.getHours();
    var greet = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
    var html =
      "<div class='s-home'>" +
      "<div class='s-statusbar'><span class='s-status-left'>" +
      "<span class='s-status-mood mood-" + weeklyMoodKey() + "' id='phoneMood'>" + moodFaceSVG(weeklyMoodKey()) + "</span>" +
      nowHM() + "</span><span>🔋</span></div>" +
      "<div class='s-top-row'>" +
      "<div class='s-greet'><h1>" + greet + " 👋</h1>" +
      "<p class='s-sub'>Promises kept today: " + state.todayKept + ". Which app are you opening?</p></div>" +
      "<div class='s-score'>" +
      "<div class='s-score-label'>POINTS</div><div class='s-score-val'>" + state.points + "</div>" +
      "</div></div>" +
      "<div class='app-grid'>" +
      "<div class='app-tile' data-app='sozumsoz' style='animation-delay:60ms'>" +
      "<div class='app-icon soz-icon'>" +
      "<img class='app-icon-img' src='" + SOZ_LOGO + "' alt='' data-mono='SS' onerror='window.__ssIconFallback(this)'>" +
      "</div>" +
      "<div class='app-name'>SÖZÜM SÖZ</div>" +
      "</div>" +
      APPS.map(function (a, i) {
        return "<div class='app-tile' data-app='" + a.id + "' style='animation-delay:" + (130 + i * 45) + "ms'>" +
          appIconHTML(a) +
          "<div class='app-name'>" + a.name + "</div>" +
          "</div>";
      }).join("") +
      "</div></div>";
    screen.innerHTML = html;
    screen.querySelectorAll(".app-tile").forEach(function (t) {
      t.addEventListener("click", function () { onTileClick(t.getAttribute("data-app")); });
    });
  }

  function onTileClick(appId) {
    if (appId === "sozumsoz") {
      if (state.consent) { openSozumsozApp(); return; }
      openSozumsozConsent();
      return;
    }
    var app = appById(appId);
    if (!app) return;
    openPromiseDialog(app);
  }

  // ---------- PHONE: inside the SÖZÜM SÖZ app ----------
  function topAppName7() {
    var since = Date.now() - 7 * 86400000;
    var sums = {}, best = null;
    state.history.forEach(function (h) {
      if (h.ts >= since) sums[h.appName] = (sums[h.appName] || 0) + h.usedMin;
    });
    Object.keys(sums).forEach(function (k) {
      if (!best || sums[k] > best.min) best = { name: k, min: sums[k] };
    });
    return best;
  }

  function sozMenuRow(label, tab) {
    return "<div class='soz-row' data-soztab='" + tab + "'><span>" + label + "</span><span class='chev'>&rsaquo;</span></div>";
  }

  function openSozumsozConsent(cb) {
    showBgNotif("soz");
    $("phoneScreen").innerHTML =
      "<div class='s-consent anim-pop'>" +
      "<div class='brand'><span class='brand-mark'><img class='brand-mark-img' src='" + SOZ_LOGO + "' alt='SÖZÜM SÖZ'></span><span class='brand-name'>SÖZÜM <b>SÖZ</b></span></div>" +
      "<h2>Privacy Notice and Explicit Consent</h2>" +
      "<div class='consent-body'>" +
      "<h4>1. Data Controller and Scope</h4>" +
      "<p>This application (SÖZÜM SÖZ) is a hackathon prototype. Pursuant to Article 10 of Turkish Law No. 6698 on the Protection of Personal Data (KVKK), the developer of the application, acting as the data controller, provides the following information.</p>" +
      "<h4>2. Personal Data Processed</h4>" +
      "<ul>" +
      "<li><b>Time-promise records:</b> app name, category, promised and actual time.</li>" +
      "<li><b>Interaction statistics:</b> points, streak, number of breaks, challenge participation.</li>" +
      "<li><b>Chat history:</b> all messages from the AI coach chat.</li>" +
      "<li><b>Device settings:</b> chosen AI provider, model, and (if you wish) API key.</li>" +
      "</ul>" +
      "<h4>3. Purposes of Processing</h4>" +
      "<ul>" +
      "<li>Monitoring digital well-being and personal reporting.</li>" +
      "<li>Running the promise/points/streak/reward motivation system.</li>" +
      "<li>Reflection support through the optional AI coach chat.</li>" +
      "</ul>" +
      "<h4>4. Legal Basis and Transfer</h4>" +
      "<ul>" +
      "<li>KVKK art. 5: the data subject's <b>explicit consent</b> (the approval you give on this screen) and legitimate interest.</li>" +
      "<li>KVKK arts. 8-9: cross-border transfer happens only when live AI is enabled and only to the provider you choose; otherwise your data is never sent to any server automatically.</li>" +
      "</ul>" +
      "<p>Your data is stored only in this device's browser storage (localStorage). It never leaves your device unless you enable live AI and enter a key in Settings. If live AI is enabled, only an anonymous session summary and the latest chat messages are sent to the provider you select (OpenAI/Gemini); your name, photos, and contact details are never collected.</p>" +
      "<h4>5. Retention Period</h4>" +
      "<p>Your data is stored on your device for as long as you use the app. It is permanently deleted when you use the \"Delete my data\" option or when browser data is cleared.</p>" +
      "<h4>6. Rights of the Data Subject (KVKK art. 11)</h4>" +
      "<ul>" +
      "<li>To learn whether your personal data is being processed,</li>" +
      "<li>To request information if it has been processed,</li>" +
      "<li>To learn the purpose of the processing and whether it is used in line with that purpose,</li>" +
      "<li>To request correction of incomplete or incorrectly processed data,</li>" +
      "<li>To request erasure or destruction of your data,</li>" +
      "<li>To request that corrections and erasures be notified to the parties to whom the data was transferred,</li>" +
      "<li>To object to automated processing and to request compensation for the damage suffered.</li>" +
      "</ul>" +
      "<p class='small'>You can exercise these rights directly with the in-app options <b>Settings → Download my data / Delete my data / Withdraw consent</b> or through your browser's privacy tools.</p>" +
      "<h4>7. Explicit Consent</h4>" +
      "<p class='muted small'>I have read the notice above; I <b>explicitly consent</b> to my data being processed for the stated purposes, to my chat messages being forwarded when necessary to the AI provider I choose, and to my personal data being processed in this scope. I can withdraw my consent at any time (Settings → Withdraw consent).</p>" +
      "</div>" +
      "<button class='btn btn-primary btn-lg' id='consentYes'>I accept, open the app</button>" +
      "<button class='btn btn-ghost btn-lg' id='consentNo'>I do not accept</button>" +
      "</div>";
    $("consentYes").addEventListener("click", function () {
      state.consent = true;
      save();
      renderSozumsozApp();
    });
    $("consentNo").addEventListener("click", function () {
      hideBgNotif();
      $("phoneScreen").innerHTML =
        "<div class='s-consent'>" +
        "<div class='brand'><span class='brand-mark'><img class='brand-mark-img' src='" + SOZ_LOGO + "' alt='SÖZÜM SÖZ'></span><span class='brand-name'>SÖZÜM <b>SÖZ</b></span></div>" +
        "<h2>App unavailable</h2>" +
        "<p>Because you did not accept the notice, the SÖZÜM SÖZ app was not opened. None of your data is collected, stored, or processed.</p>" +
        "<p class='muted small'>If you wish, you can read the notice again and change your mind.</p>" +
        "<button class='btn btn-primary btn-lg' id='consentBack'>Read the notice again</button>" +
        "<button class='btn btn-ghost btn-lg' id='consentExit'>Back to home screen</button>" +
        "</div>";
      $("consentBack").addEventListener("click", function () { openSozumsozConsent(); });
      $("consentExit").addEventListener("click", renderHome);
    });
  }

  function openSozumsozApp() {
    if (!state.consent) { openSozumsozConsent(); return; }
    renderSozumsozApp();
  }

  function renderSozumsozApp() {
    var mood = weeklyMood();
    var top = topAppName7();
    $("phoneScreen").innerHTML =
      "<div class='s-soz'>" +
      "<div class='soz-header'>" +
      "<span class='soz-title'>SÖZÜM SÖZ</span>" +
      "<span class='soz-mood'>This week " + mood.emoji + " " + mood.label + "</span>" +
      "</div>" +
      "<div class='soz-stats'>" +
      "<div class='soz-stat'><b>" + state.points + "</b><span>Points</span></div>" +
      "<div class='soz-stat'><b>" + state.streak + "</b><span>Streak</span></div>" +
      "<div class='soz-stat'><b>" + state.todayKept + "</b><span>Kept today</span></div>" +
      "</div>" +
      "<div class='soz-top'>" + (top
        ? "Most used in the last 7 days: <b>" + top.name + "</b> (" + top.min + " min)"
        : "No data yet. Make a promise to start with your " + state.points + " points.") + "</div>" +
      "<div class='soz-menu'>" +
      sozMenuRow("Status", "stats") +
      sozMenuRow("Charts", "charts") +
      sozMenuRow("Reward Catalog", "rewards") +
      sozMenuRow("Monthly Draw", "draw") +
      sozMenuRow("Reflection (AI)", "ai") +
      "</div>" +
      "<button class='btn btn-ghost btn-lg' id='sozBack'>Go back</button>" +
      "</div>";
    $("sozBack").addEventListener("click", function () { hideBgNotif(); renderHome(); });
    $("phoneScreen").querySelectorAll("[data-soztab]").forEach(function (row) {
      row.addEventListener("click", function () { setTab(row.getAttribute("data-soztab")); });
    });
    showBgNotif("soz");
  }

  // ---------- PHONE: time-promise dialog (in-phone sub page) ----------
  function openPromiseDialog(app) {
    var chosen = null;
    var opts = TIME_OPTIONS.map(function (m) {
      return "<button class='time-btn dur-chip' data-min='" + m + "'>" + m + "<span>min</span></button>";
    }).join("");
    var sc = $("phoneScreen");
    sc.innerHTML =
      "<div class='s-sheet-backdrop' id='promiseScrim'></div>" +
      "<div class='s-sheet'>" +
      "<div class='sheet-grab'></div>" +
      "<div class='sheet-head'>" +
      appIconHTML(app, "sheet-appicon") +
      "<div class='sheet-meta'><div class='sheet-apptitle'>" + app.name + "</div>" +
      "<span class='sheet-cat'>" + CATEGORY_LABELS[app.category] + "</span></div>" +
      "</div>" +
      "<div class='sheet-q'>How many minutes do you <b>promise?</b></div>" +
      "<div class='dur-chips' id='durChips'>" + opts + "</div>" +
      "<div class='dur-custom'>" +
      "<input type='number' id='customMin' min='1' max='240' placeholder='Custom time (min)'>" +
      "<button class='dur-dice' id='durSuggest' title='Suggest a random time'>🎲</button>" +
      "</div>" +
      "<div class='sheet-reward'><span>If you keep your promise: <b class='p-plus'>+3 points</b></span><span>If you exceed it: <b class='p-minus'>−5 points</b></span></div>" +
      "<button class='btn btn-primary btn-lg btn-glow' id='promiseOk' disabled>Promise</button>" +
      "<button class='sheet-link' id='promiseNo'>Cancel</button>" +
      "</div>";
    var ok = $("promiseOk");
    var custom = $("customMin");
    var dice = $("durSuggest");
    var btnPromise = function (min) {
      chosen = min;
      document.querySelectorAll(".dur-chip").forEach(function (b) {
        b.classList.toggle("sel", parseInt(b.getAttribute("data-min"), 10) === min);
      });
      if (ok) { ok.textContent = "Promise (" + min + " min)"; ok.disabled = false; }
    };
    document.querySelectorAll(".dur-chip").forEach(function (b) {
      b.addEventListener("click", function () { btnPromise(parseInt(b.getAttribute("data-min"), 10)); });
    });
    custom.addEventListener("input", function () {
      var v = parseInt(custom.value, 10);
      if (v >= 1 && v <= 240) btnPromise(v);
    });
    dice.addEventListener("click", function () {
      var v = 2 + Math.floor(Math.random() * 9);
      custom.value = v;
      btnPromise(v);
    });
    ok.addEventListener("click", function () {
      if (chosen) { renderHome(); enterApp(app, chosen); }
    });
    $("promiseNo").addEventListener("click", renderHome);
    $("promiseScrim").addEventListener("click", renderHome);
  }

  // ---------- entering an app ----------
  function enterApp(app, minutes) {
    checkHopGuard(app);
    session = {
      appId: app.id,
      appName: app.name,
      category: app.category,
      promisedMin: minutes,
      startedAt: Date.now(),
      elapsedSec: 0,
      usedMin: 0,
      overshootNotified: false
    };
    renderAppScreen();
    showBgNotif();
    if (tickerId) clearInterval(tickerId);
    tickerId = setInterval(tick, 1000);
  }

  function checkHopGuard(app) {
    var last = state.lastClose;
    if (!last) return;
    var withinWindow = (Date.now() - last.ts) <= HOP_WINDOW_MS;
    if (last.result === "broken_exceed") {
      notify("Take a break", "You opened a new app right after closing a session that ended in an overshoot. Step away from the screen for a few minutes.", "warn");
      state.lastClose = { ts: Date.now(), result: "broken_exceed" };
      save();
      return;
    }
    if (last.result === "kept" && withinWindow) {
      recordResult("broken_hop", PENALTY, {
        appId: app.id, appName: app.name, category: app.category, promisedMin: 1, usedMin: 1
      });
      notify("App hop detected", "You opened " + app.name + " right after closing it. Hopping between apps breaks your promise; points were deducted.", "danger");
      requestCoach("hop", { appName: app.name, category: app.category, promisedMin: 0, overMin: 0 });
      state.lastClose = { ts: Date.now(), result: "broken_hop" };
      save();
      renderHeader();
      renderStats();
    }
  }

  // ---------- AI coach: dynamic notification + break ----------
  function requestCoach(type, extra) {
    var s = session;
    var opts = {
      type: type,
      appName: s ? s.appName : (extra && extra.appName) || "",
      category: s ? s.category : (extra && extra.category) || "",
      promisedMin: s ? s.promisedMin : 0,
      overMin: (s && s.usedMin > s.promisedMin) ? (s.usedMin - s.promisedMin) : 0,
      hour: new Date().getHours(),
      streak: state.streak
    };
    AI.generateCoach(opts, state.ai).then(function (res) {
      var m = res.msg;
      var el = notify(m.title, m.body + " " + m.breakOffer + " (AI-generated)", type === "overshoot" ? "warn" : "danger", [
        {
          label: "Start break (+" + m.points + " points)",
          cls: "btn-success",
          onClick: function () { dismissNotif(el); startMicroBreak(m.points, m.breakOffer); }
        },
        {
          label: "Not now",
          cls: "btn-ghost",
          onClick: function () { dismissNotif(el); }
        }
      ]);
    }).catch(function (err) {
      notify("Could not generate notification", err.message, "info");
    });
  }

  // ---------- micro-break ----------
  function startMicroBreak(points, offerText) {
    if (!session) {
      notify("Break", "Break offer cancelled because the session is closed; it will be available in the next session.", "info");
      return;
    }
    var sc = $("phoneScreen");
    var end = Date.now() + BREAK_SECONDS * 1000;
    sc.innerHTML =
      "<div class='s-break'>" +
      "<div class='bk-ring'><div class='bk-count' id='breakCount'>" + BREAK_SECONDS + "</div></div>" +
      "<div class='bk-text'>" + offerText + "</div>" +
      "<div class='bk-hint'>You'll earn +" + points + " points when the break ends.</div>" +
      "<div class='row'><button class='btn btn-warn' id='bkCancel'>Not a break</button></div>" +
      "</div>";
    $("bkCancel").addEventListener("click", function () { clearInterval(bkTimer); renderAppScreen(); });
    var bkTimer = setInterval(function () {
      var left = Math.max(0, Math.ceil((end - Date.now()) / 1000));
      var c = $("breakCount");
      if (c) c.textContent = left;
      if (left <= 0) {
        clearInterval(bkTimer);
        finishMicroBreak(points);
      }
    }, 250);
  }

  function finishMicroBreak(points) {
    state.points += points;
    floatPoints(points);
    state.breaksTaken++;
    state.breaksLog.push({ ts: Date.now() });
    state.breaksLog = state.breaksLog.slice(-60);
    pushFeed("Break completed: +" + points + " points");
    notify("Break completed", "You earned +" + points + " points 🎉", "good");
    save();
    renderHeader();
    if (session) renderAppScreen(); else renderHome();
    renderStats();
  }

  // ---------- time ticker ----------
  function tick() {
    if (!session) return;
    session.elapsedSec += 1;
    var speed = state.speedFast ? 1 : 1 / 60;
    session.usedMin = Math.floor(session.elapsedSec * speed + 1e-9);
    if (!session.overshootNotified && session.usedMin > session.promisedMin) {
      session.overshootNotified = true;
      requestCoach("overshoot");
    }
    renderAppTicker();
  }

  function renderAppTicker() {
    var el = $("appTimerCard");
    if (!el || !session) return;
    var over = session.usedMin > session.promisedMin;
    var remain = Math.max(0, session.promisedMin - session.usedMin);
    var pct = Math.min(100, Math.round(session.usedMin / session.promisedMin * 100));
    el.className = "timer-card" + (over ? " over" : "");
    el.innerHTML =
      "<div class='timer-row'>" +
      "<div class='timer-ring' style='--p:" + pct + "%'>" +
      "<div class='timer-ring-in'>" +
      "<div class='timer-num'>" + (over ? "+" + (session.usedMin - session.promisedMin) : remain) + "</div>" +
      "<div class='timer-num-label'>" + (over ? "min over" : "min left") + "</div>" +
      "</div></div>" +
      "<div class='timer-info'>" +
      "<div class='timer-info-row'><span>Promise</span><b>" + session.promisedMin + " min</b></div>" +
      "<div class='timer-info-row'><span>Used</span><b>" + session.usedMin + " min</b></div>" +
      "<div class='timer-tip'>If you keep this promise: <b>+3 points</b></div>" +
      "</div></div>";
    if (over && !$("overBanner")) {
      var sc = $("phoneScreen");
      var feed = sc.querySelector(".mock-feed");
      if (feed) {
        var b = document.createElement("div");
        b.id = "overBanner";
        b.className = "over-banner";
        b.innerHTML = "⏰ Time exceeded — close the screen and take a short break";
        feed.insertBefore(b, feed.firstChild);
      }
    }
  }

  // ---------- app screen ----------
  function renderAppScreen() {
    var sc = $("phoneScreen");
    var app = appById(session.appId);
    var glyphs = CATEGORY_GLYPHS[app.category] || ["✨", "💬", "🚀"];
    var feed = "";
    for (var i = 0; i < 3; i++) {
      feed +=
        "<div class='post-card'>" +
        "<div class='post-head'><span class='post-ava' style='background:linear-gradient(135deg," + app.color + ",#0f172a)'>" + app.monogram + "</span>" +
        "<div class='post-id'><div class='post-user'>" + app.name + "</div><div class='post-time'>1 second ago · sponsored</div></div>" +
        "<span class='post-more'>•••</span></div>" +
        "<div class='post-media' style='background:linear-gradient(135deg," + MOCK_MEDIA[(i * 3) % MOCK_MEDIA.length] + ",#0f172a)'>" + glyphs[i] + "</div>" +
        "<div class='post-actions'><span>♥ " + (128 + i * 97) + "</span><span>💬 " + (23 + i * 18) + "</span><span>↗ " + (34 + i * 21) + "</span></div>" +
        "</div>";
    }
    sc.innerHTML =
      "<div class='s-app'>" +
      "<div class='appbar'>" +
      "<button class='appbar-back' id='appBackBtn'>‹</button>" +
      appIconHTML(app, "appbar-icon") +
      "<div class='appbar-mid'><div class='appbar-name'>" + app.name + "</div><div class='appbar-cat'>" + CATEGORY_LABELS[app.category] + "</div></div>" +
      "<span class='appbar-badge'>PROMISE active</span>" +
      "</div>" +
      "<div id='appTimerCard' class='timer-card'></div>" +
      "<div class='mock-feed'>" + feed + "</div>" +
      "<div class='app-actions'>" +
      "<button class='btn btn-success btn-lg btn-glow' id='btnKeep'>Keep my promise and close</button>" +
      "<button class='btn btn-ghost btn-lg' id='btnSwitch'>Switch to another app</button>" +
      "</div></div>";
    $("appBackBtn").addEventListener("click", function () { finishSession(false); });
    $("btnKeep").addEventListener("click", function () { finishSession(false); });
    $("btnSwitch").addEventListener("click", function () {
      if (session && session.usedMin > session.promisedMin) {
        notify("Time exceeded", "You exceeded your time; the session closes as broken and points are deducted.", "danger");
        finishSession(false);
      } else {
        notify("App hop detected", "Switching to another app breaks your promise; points are deducted.", "warn");
        finishSession(true);
      }
    });
    renderAppTicker();
  }

  // ---------- session end ----------
  function finishSession(hopFlag) {
    if (!session) return;
    var s = session;
    session = null;
    if (tickerId) { clearInterval(tickerId); tickerId = null; }
    var result = hopFlag ? "broken_hop"
      : (s.usedMin > s.promisedMin ? "broken_exceed" : "kept");
    var delta = result === "kept" ? REWARD_KEPT : PENALTY;
    recordResult(result, delta, s);
    state.lastClose = { ts: Date.now(), result: result };
    save();
    renderHome();
    hideBgNotif();
    renderHeader();
    renderStats();
  }

  function recordResult(result, delta, info) {
    var usedMin = info.usedMin || 0;
    var promisedMin = info.promisedMin || 0;
    var entry = {
      ts: Date.now(),
      appId: info.appId,
      appName: info.appName,
      category: info.category,
      promisedMin: promisedMin,
      usedMin: usedMin,
      result: result,
      delta: delta
    };
    state.history.unshift(entry);
    state.history = state.history.slice(0, 120);
    state.points = Math.max(0, state.points + delta);
    if (delta !== 0) floatPoints(delta);

    if (result === "kept") {
      state.kept++;
      state.todayKept++;
      state.streak++;
      if (state.streak > state.bestStreak) state.bestStreak = state.streak;
      if (MILESTONES[state.streak] && state.milestones.indexOf(state.streak) === -1) {
        state.milestones.push(state.streak);
        state.points += MILESTONES[state.streak];
        floatPoints(MILESTONES[state.streak]);
        notify("Streak bonus", "You kept " + state.streak + " promises in a row! +" + MILESTONES[state.streak] + " bonus points 🎉", "good");
        pushFeed("Streak bonus: " + state.streak + " promises in a row, +" + MILESTONES[state.streak] + " points");
      }
      if (state.todayKept >= DAILY_CHALLENGE.target && !state.challengeClaimed) {
        notify("Promise of the day complete", "You kept " + DAILY_CHALLENGE.target + " promises today; claim an extra +" + DAILY_CHALLENGE.reward + " points from the Status tab 👏", "good");
      }
    } else {
      state.streak = 0;
      if (result === "broken_exceed") state.brokenExceed++;
      else state.brokenHop++;
    }
    pushFeed((delta >= 0 ? "+" : "") + delta + " points | " + (result === "kept" ? "you kept your promise" : result === "broken_exceed" ? "you exceeded your time" : "you jumped to another app") + " (" + info.appName + ")");
  }

  // ---------- STATUS tab ----------
  function sessionsSince(days) {
    var cutoff = Date.now() - days * 86400000;
    return state.history.filter(function (h) { return h.ts >= cutoff; });
  }

  function renderStats() {
    var cards = $("statCards");
    var todaySessions = sessionsSince(1).filter(function (h) { return dailyOf(h.ts) === todayKey(); });
    var todayMin = todaySessions.reduce(function (a, h) { return a + h.usedMin; }, 0);
    var streakTxt = state.streak + (state.streak === 1 ? " promise" : " promises");
    var bestTxt = state.bestStreak + (state.bestStreak === 1 ? " promise" : " promises");
    var stat = [
      { label: "Your points", value: state.points, cls: "s-ok" },
      { label: "Current streak", value: streakTxt, cls: "s-amber" },
      { label: "Best streak", value: bestTxt, cls: "" },
      { label: "Promises kept", value: state.kept, cls: "s-ok" },
      { label: "Broken (overshoot)", value: state.brokenExceed, cls: "s-bad" },
      { label: "Broken (hop)", value: state.brokenHop, cls: "s-bad" },
      { label: "Breaks completed", value: state.breaksTaken || 0, cls: "s-ok" },
      { label: "Today's usage", value: todayMin + " min", cls: "" }
    ];
    cards.innerHTML = stat.map(function (s) {
      return "<div class='stat-card " + s.cls + "'><div class='stat-label'>" + s.label + "</div><div class='stat-value'>" + s.value + "</div></div>";
    }).join("");

    var last7 = sessionsSince(7);
    var cat = {};
    last7.forEach(function (h) { cat[h.category] = (cat[h.category] || 0) + h.usedMin; });
    var sorted = Object.keys(cat).map(function (k) { return { name: CATEGORY_LABELS[k] || k, min: cat[k] }; })
      .sort(function (a, b) { return b.min - a.min; });
    var maxMin = sorted.length ? sorted[0].min : 0;
    var barsEl = $("categoryBars");
    if (!sorted.length) {
      barsEl.innerHTML = "<div class='muted'>No data yet.</div>";
    } else {
      barsEl.innerHTML = sorted.map(function (c) {
        var w = maxMin ? Math.round(c.min / maxMin * 100) : 0;
        return "<div class='cat-bar-row'><span class='cat-bar-label'>" + c.name + "</span>" +
          "<div class='cat-bar-track'><div class='cat-bar-fill' style='width:" + w + "%'></div></div>" +
          "<span class='cat-bar-min'>" + c.min + " min</span></div>";
      }).join("");
    }

    renderChallenge();
    renderCharts();
  }

  function dailyOf(ts) {
    var d = new Date(ts);
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }

  function renderChallenge() {
    var el = $("challengeCard");
    var prog = Math.min(state.todayKept, DAILY_CHALLENGE.target);
    var done = state.todayKept >= DAILY_CHALLENGE.target;
    var html =
      "<h3>" + DAILY_CHALLENGE.title + "</h3>" +
      "<p>" + DAILY_CHALLENGE.text + "</p>" +
      "<div class='challenge-box'><div class='challenge-progress'>" +
      "<div class='cnt'>" + prog + " / " + DAILY_CHALLENGE.target + " promises kept</div>" +
      "<div class='progress'><div style='width:" + Math.round(prog / DAILY_CHALLENGE.target * 100) + "%'></div></div>" +
      "</div>";
    if (done) {
      html += state.challengeClaimed
        ? "<button class='btn' disabled>Reward claimed (+" + DAILY_CHALLENGE.reward + ")</button>"
        : "<button class='btn btn-primary' id='btnClaim'>Claim reward (+" + DAILY_CHALLENGE.reward + " points)</button>";
    }
    html += "</div>";
    el.innerHTML = html;
    if (done && !state.challengeClaimed) {
      $("btnClaim").addEventListener("click", function () {
        state.challengeClaimed = true;
        state.points += DAILY_CHALLENGE.reward;
        pushFeed("Promise-of-the-day reward: +" + DAILY_CHALLENGE.reward + " points");
        notify("Reward added", "Promise-of-the-day reward of +" + DAILY_CHALLENGE.reward + " points added to your account.", "good");
        save();
        renderHeader();
        renderStats();
      });
    }
  }

  // ---------- WEEKLY CHALLENGES ----------
  function ensureWeeklyChallenges() {
    if (!state.challenges) state.challenges = { week: null, joined: [], claimed: [] };
    var wk = weekIdx(Date.now());
    if (state.challenges.week !== wk) {
      state.challenges = { week: wk, joined: [], claimed: [] };
    }
  }

  function challengeCurrent(c) {
    var since = Date.now() - 7 * 86400000;
    var h7 = state.history.filter(function (h) { return h.ts >= since; });
    switch (c.metric) {
      case "weeklyMin":
        return h7.reduce(function (a, h) { return a + h.usedMin; }, 0);
      case "keptCount":
        return h7.filter(function (h) { return h.result === "kept"; }).length;
      case "breaks":
        return state.breaksLog.filter(function (b) { return b.ts >= since; }).length;
      case "distinctApps": {
        var set = {};
        h7.forEach(function (h) { set[h.appId] = 1; });
        return Object.keys(set).length;
      }
      case "overshootCount":
        return h7.filter(function (h) { return h.result === "broken_exceed"; }).length;
    }
    return 0;
  }

  function challengeMet(c, cur, hasData) {
    if (c.direction === "less") return hasData && cur < c.target;
    return cur >= c.target;
  }

  function renderChallenges() {
    var el = $("challengeList");
    if (!el) return;
    ensureWeeklyChallenges();
    var joined = state.challenges.joined;
    var claimed = state.challenges.claimed;
    var has7 = state.history.some(function (h) { return (Date.now() - h.ts) <= 7 * 86400000; });
    el.innerHTML = CHALLENGES.map(function (c) {
      var cur = challengeCurrent(c);
      var met = challengeMet(c, cur, has7);
      var isJ = joined.indexOf(c.id) !== -1;
      var isC = claimed.indexOf(c.id) !== -1;
      var barPct = Math.min(100, Math.round(Math.min(cur, c.target) / c.target * 100));
      var stateTxt, btn;
      if (isC) {
        stateTxt = "Completed ✓";
        btn = "<button class='btn' disabled>Reward claimed (+" + c.reward + " points)</button>";
      } else if (!isJ) {
        stateTxt = c.direction === "less"
          ? "Current: " + cur + " " + c.unit + " (target: < " + c.target + " " + c.unit + ")"
          : "Current: " + cur + " / " + c.target + " " + c.unit;
        btn = "<button class='btn btn-primary' data-join='" + c.id + "'>Join challenge</button>";
      } else if (met) {
        stateTxt = "Condition met!";
        btn = "<button class='btn btn-success' data-claim='" + c.id + "'>Claim reward (+" + c.reward + " points)</button>";
      } else {
        stateTxt = c.direction === "less"
          ? "Progress: " + cur + " " + c.unit + " (target < " + c.target + ")"
          : "Progress: " + cur + " / " + c.target + " " + c.unit;
        btn = "<button class='btn' disabled>Joined</button>";
      }
      return "<div class='ch-card'>" +
        "<div class='ch-head'><div class='ch-title'>" + c.title + "</div><div class='ch-reward'>+" + c.reward + " points</div></div>" +
        "<p class='ch-text'>" + c.text + "</p>" +
        "<div class='ch-progress'><div class='ch-bar'><div style='width:" + barPct + "%'></div></div></div>" +
        "<div class='ch-cur'>" + stateTxt + "</div>" +
        "<div class='ch-action'>" + btn + "</div>" +
        "</div>";
    }).join("");

    el.querySelectorAll("[data-join]").forEach(function (b) {
      b.addEventListener("click", function () {
        state.challenges.joined.push(b.getAttribute("data-join"));
        save();
        renderChallenges();
      });
    });
    el.querySelectorAll("[data-claim]").forEach(function (b) {
      b.addEventListener("click", function () {
        var c = CHALLENGES.filter(function (x) { return x.id === b.getAttribute("data-claim"); })[0];
        if (!c) return;
        state.challenges.joined = state.challenges.joined.filter(function (x) { return x !== c.id; });
        state.challenges.claimed.push(c.id);
        state.points += c.reward;
        pushFeed("Weekly challenge completed: " + c.title + " · +" + c.reward + " points");
        notify("Challenge completed", c.title + ": +" + c.reward + " points added to your account.", "good");
        save();
        renderHeader();
        renderStats();
        renderChallenges();
      });
    });
  }

  // ---------- CHARTS tab ----------
  var DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  var CATEGORY_COLORS = { social: "#e1306c", video: "#dc2626", messaging: "#16a34a", streaming: "#b91c1c", gaming: "#7c3aed", music: "#15803d", news: "#ea580c" };

  function minOnDayKey(key) {
    var m = 0;
    state.history.forEach(function (h) { if (dailyOf(h.ts) === key) m += h.usedMin; });
    return m;
  }

  function dayKeyOffset(offset) {
    var d = new Date();
    d.setHours(12, 0, 0, 0);
    d.setDate(d.getDate() + offset);
    return dailyOf(d.getTime());
  }

  function pctOf(v, max) { return max > 0 ? Math.round(v / max * 100) : 0; }

  function weekIdx(ts) {
    var d = new Date(ts);
    d.setHours(0, 0, 0, 0);
    var dow = (d.getDay() + 6) % 7;
    d.setDate(d.getDate() - dow);
    return Math.floor(d.getTime() / (7 * 86400000));
  }

  function renderCharts() {
    renderTodayCompare();
    renderLast7Days();
    renderLast4Weeks();
    renderCategoryDonut();
    renderTopApps();
  }

  function renderTodayCompare() {
    var el = $("chartTodayVsWeek");
    if (!el) return;
    var todayMin = minOnDayKey(todayKey());
    var lastMin = minOnDayKey(dayKeyOffset(-7));
    var maxVal = Math.max(todayMin, lastMin, 1);
    var todayName = DAY_NAMES[new Date().getDay()];
    var lastName = DAY_NAMES[new Date(Date.now() - 7 * 86400000).getDay()];
    var todayH = todayMin > 0 ? Math.max(8, Math.round(todayMin / maxVal * 110)) : 0;
    var lastH = lastMin > 0 ? Math.max(8, Math.round(lastMin / maxVal * 110)) : 0;
    var dif = todayMin - lastMin;
    var diffTxt =
      dif === 0
        ? "Your usage today matches the same day last week (" + todayMin + " min)."
        : dif > 0
          ? "Today you spent " + dif + " min more than the same day last week."
          : "Today you spent " + (-dif) + " min less than the same day last week.";
    el.innerHTML =
      "<h3>Today vs the same day last week</h3>" +
      "<div class='cmp'>" +
      "<div class='cmp-col'><div class='cmp-label'>Today · " + todayName + "</div>" +
      "<div class='cmp-track'><div class='cmp-bar' style='height:" + todayH + "px'></div></div>" +
      "<div class='cmp-value'>" + todayMin + " min</div></div>" +
      "<div class='cmp-col'><div class='cmp-label'>Last week · " + lastName + "</div>" +
      "<div class='cmp-track'><div class='cmp-bar mut' style='height:" + lastH + "px'></div></div>" +
      "<div class='cmp-value'>" + lastMin + " min</div></div>" +
      "</div>" +
      "<div class='cmp-diff'>" + diffTxt + "</div>";
  }

  function renderLast7Days() {
    var el = $("chartLast7");
    if (!el) return;
    var maxMin = 1, days = [];
    for (var i = -6; i <= 0; i++) {
      var k = dayKeyOffset(i);
      var m = minOnDayKey(k);
      if (m > maxMin) maxMin = m;
      days.push({ key: k, min: m, name: DAY_NAMES[new Date(k + "T12:00:00").getDay()], today: i === 0 });
    }
    var total7 = days.reduce(function (a, d) { return a + d.min; }, 0);
    el.innerHTML = "<h3>Last 7 days - screen usage</h3>" +
      (total7 === 0
        ? "<div class='muted'>No data yet.</div>"
        : "<div class='days'>" + days.map(function (d) {
            return "<div class='day-col" + (d.today ? " today" : "") + "'>" +
              "<div class='day-min'>" + d.min + "</div>" +
              "<div class='day-track'><div class='day-bar' style='height:" + Math.max(3, Math.round(d.min / maxMin * 100)) + "px'></div></div>" +
              "<div class='day-name'>" + d.name + "</div>" +
              "</div>";
          }).join("") + "</div>" +
          "<p class='muted small' style='margin-top:8px'>The orange bar marks today.</p>");
  }

  function renderLast4Weeks() {
    var el = $("chartWeeks");
    if (!el) return;
    var sums = {};
    state.history.forEach(function (h) {
      var w = weekIdx(h.ts);
      sums[w] = (sums[w] || 0) + h.usedMin;
    });
    var thisW = weekIdx(Date.now());
    var labels = ["3 weeks ago", "2 weeks ago", "Last week", "This week"];
    var data = labels.map(function (l, i) { return { label: l, min: sums[thisW - 3 + i] || 0 }; });
    var maxMin = 1;
    data.forEach(function (d) { if (d.min > maxMin) maxMin = d.min; });
    var totalW = data.reduce(function (a, d) { return a + d.min; }, 0);
    el.innerHTML = "<h3>Weekly comparison (last 4 weeks)</h3>" +
      (totalW === 0
        ? "<div class='muted'>No data yet.</div>"
        : "<div class='weeks'>" + data.map(function (d) {
            return "<div class='week-col'><div class='week-min'>" + d.min + " min</div>" +
              "<div class='week-track'><div class='week-bar" + (d.label === "This week" ? " now" : "") + "' style='height:" + Math.max(4, Math.round(d.min / maxMin * 100)) + "px'></div></div>" +
              "<div class='week-name'>" + d.label + "</div></div>";
          }).join("") + "</div>");
  }

  function renderCategoryDonut() {
    var el = $("chartCategories");
    if (!el) return;
    var since = Date.now() - 7 * 86400000;
    var sums = {};
    state.history.forEach(function (h) { if (h.ts >= since) sums[h.category] = (sums[h.category] || 0) + h.usedMin; });
    var data = Object.keys(sums).map(function (k) {
      return { name: CATEGORY_LABELS[k] || k, color: CATEGORY_COLORS[k] || "#6366f1", min: sums[k] };
    }).sort(function (a, b) { return b.min - a.min; });
    var total = data.reduce(function (a, d) { return a + d.min; }, 0);
    if (!total) { el.innerHTML = "<h3>Category breakdown (last 7 days)</h3><div class='muted'>No data yet.</div>"; return; }
    var size = 140, c = size / 2, r = 48, C = 2 * Math.PI * r;
    var acc = 0, parts = "";
    data.forEach(function (d) {
      var frac = d.min / total;
      parts += "<circle r='" + r + "' cx='" + c + "' cy='" + c + "' fill='none' stroke='" + d.color + "' stroke-width='24' " +
        "stroke-dasharray='" + (frac * C) + " " + C + "' stroke-dashoffset='" + (-(acc * C + C * 0.25)) + "'/>";
      acc += frac;
    });
    var legend = data.map(function (d) {
      return "<div class='legend-row'><span class='dot' style='background:" + d.color + "'></span>" +
        d.name + "<span class='legend-pct'>%" + Math.round(d.min / total * 100) + " (" + d.min + " min)</span></div>";
    }).join("");
    el.innerHTML = "<h3>Category breakdown (last 7 days)</h3>" +
      "<div class='donut-wrap'>" +
      "<div class='donut'><svg viewBox='0 0 " + size + " " + size + "'>" + parts + "</svg>" +
      "<div class='donut-center'><b>" + total + "</b><span>min</span></div></div>" +
      "<div class='legend'>" + legend + "</div>" +
      "</div>";
  }

  function renderTopApps() {
    var el = $("chartTopApps");
    if (!el) return;
    var since = Date.now() - 7 * 86400000;
    var sums = {};
    state.history.forEach(function (h) { if (h.ts >= since) sums[h.appName] = (sums[h.appName] || 0) + h.usedMin; });
    var data = Object.keys(sums).map(function (k) { return { name: k, min: sums[k] }; })
      .sort(function (a, b) { return b.min - a.min; })
      .slice(0, 6);
    var maxMin = data.length ? data[0].min : 1;
    el.innerHTML = "<h3>Most used apps (last 7 days)</h3>" +
      (data.length
        ? "<div class='cat-bars'>" + data.map(function (a) {
            return "<div class='cat-bar-row'><span class='cat-bar-label'>" + a.name + "</span>" +
              "<div class='cat-bar-track'><div class='cat-bar-fill' style='width:" + pctOf(a.min, maxMin) + "%'></div></div>" +
              "<span class='cat-bar-min'>" + a.min + " min</span></div>";
          }).join("") + "</div>"
        : "<div class='muted'>No data yet.</div>");
  }

  // ---------- REWARDS tab ----------
  function renderRewards() {
    var grid = $("rewardGrid");
    grid.innerHTML = REWARDS.map(function (r) {
      var affordable = state.points >= r.price;
      return "<div class='reward-card'>" +
        "<div class='reward-icon'>" + r.monogram + "</div>" +
        "<div class='reward-badge'>Yeşilay reward</div>" +
        "<div class='reward-name'>" + r.name + "</div>" +
        "<div class='reward-desc'>" + r.desc + "</div>" +
        "<div class='reward-price'>" + r.price + " points</div>" +
        "<button class='btn " + (affordable ? "btn-success" : "") + "' data-reward='" + r.id + "' " + (affordable ? "" : "disabled") + ">Get</button>" +
        "</div>";
    }).join("");
    grid.querySelectorAll("[data-reward]").forEach(function (b) {
      b.addEventListener("click", function () {
        var r = REWARDS.filter(function (x) { return x.id === b.getAttribute("data-reward"); })[0];
        if (state.points >= r.price) {
          state.points -= r.price;
          state.rewardOrders.push({ id: r.id, name: r.name, ts: Date.now(), price: r.price });
          pushFeed("Reward order: " + r.name + " (" + r.price + " points)");
          notify("Order confirmed", "Your " + r.name + " order has been forwarded to Yeşilay (prototype scenario).", "good");
          save();
          renderHeader();
          renderRewards();
        }
      });
    });
    var mine = $("myRewardsList");
    mine.className = "muted";
    mine.innerHTML = state.rewardOrders.length
      ? state.rewardOrders.slice().reverse().map(function (o) {
          return "<div class='feed-item'>" + nowHM(o.ts) + " - " + o.name + " (" + o.price + " points)</div>";
        }).join("")
      : "You haven't placed any orders yet.";
  }

  // ---------- DRAW tab ----------
  function monthKeyOf(ts) { return dailyOf(ts).slice(0, 7); }

  function computeMonthStats() {
    var mk = todayKey().slice(0, 7);
    var kept = 0, broken = 0;
    state.history.forEach(function (h) {
      if (monthKeyOf(h.ts) === mk) {
        if (h.result === "kept") kept++;
        else broken++;
      }
    });
    return { kept: kept, broken: broken, mk: mk };
  }

  function renderDraw() {
    var ms = computeMonthStats();
    var eligible = ms.broken === 0 && ms.kept >= DRAW_TARGET_KEPT;
    var entered = state.lotteryEnteredMonth === ms.mk;
    var pct = Math.min(100, Math.round(ms.kept / DRAW_TARGET_KEPT * 100));
    $("monthProgress").innerHTML =
      "<div class='cat-bar-row'><span class='cat-bar-label'>Promises kept</span>" +
      "<div class='cat-bar-track'><div class='cat-bar-fill' style='width:" + pct + "%'></div></div>" +
      "<span class='cat-bar-min'>" + ms.kept + "/" + DRAW_TARGET_KEPT + "</span></div>";
    $("monthStatus").textContent =
      ms.broken === 0
        ? "No broken promises this month. Kept: " + ms.kept + " / " + DRAW_TARGET_KEPT
        : "Broken this month: " + ms.broken + ". To enter the draw, you must have no broken promises.";
    $("prizeList").innerHTML = DRAW_PRIZES.map(function (p) { return "<li>" + p + "</li>"; }).join("");
    var btn = $("btnEnterDraw");
    btn.disabled = !(eligible && !entered);
    btn.textContent = entered ? "You entered this month's draw" : eligible ? "Enter the Draw" : "Conditions not met";
    $("drawEnteredNote").textContent = entered
      ? "Your entry is recorded. Results are announced at the end of the month under the Yeşilay protocol (scenario)."
      : "";
  }

  $("btnEnterDraw").addEventListener("click", function () {
    var mk = todayKey().slice(0, 7);
    if (state.lotteryEnteredMonth !== mk) {
      state.lotteryEnteredMonth = mk;
      pushFeed("You entered the monthly draw (" + mk + ")");
      notify("You're in the draw", "You kept all your promises this month. Good luck!", "good");
      save();
      renderDraw();
    }
  });

  // ---------- AI tab ----------
  function renderAIStatus() {
    var el = $("aiStatus");
    if (state.ai.live && state.ai.apiKey) {
      el.innerHTML = "<span class='live-dot'></span> Live AI · " + providerLabel() + " · " + esc(state.ai.model) + " @ " + esc(state.ai.baseUrl);
      el.className = "ai-status live";
    } else {
      el.textContent = "Mode: AI connection off - template generation (add an API key in Settings for live).";
      el.className = "ai-status muted";
    }
  }

  function sessionsDaily() {
    return state.history.filter(function (h) { return dailyOf(h.ts) === todayKey(); });
  }

  function runAI(kind) {
    var out = $("aiOutput");
    var wrap = $("aiPromptWrap");
    out.className = "ai-output busy";
    out.innerHTML = "<span>AI is thinking</span><span class='ai-dots'></span>";
    wrap.innerHTML = "";
    var sessions = kind === "daily" ? sessionsDaily() : sessionsSince(7);
    AI.generate(kind, sessions, state.ai).then(function (res) {
      out.className = "ai-output";
      var tag = res.source === "live" ? "Live AI response" : res.source === "live-error" ? "Live call failed, showing template: " + res.error : "Template generation (live connection off)";
      var tagLine = document.createElement("div");
      tagLine.className = "muted small";
      tagLine.style.marginBottom = "8px";
      tagLine.textContent = tag;
      var body = document.createElement("div");
      body.style.whiteSpace = "pre-wrap";
      out.classList.remove("busy");
      out.textContent = "";
      out.appendChild(tagLine);
      out.appendChild(body);
      typeText(body, res.text, function () {
        var stamp = document.createElement("div");
        stamp.className = "ai-stamp";
        stamp.textContent = AI_STAMP;
        out.appendChild(stamp);
      });
      var btn = document.createElement("button");
      btn.className = "prompt-toggle";
      btn.textContent = "Show the prompt used (+ design rationale)";
      btn.addEventListener("click", function () {
        var existing = wrap.querySelector(".prompt-box");
        if (existing) { existing.remove(); btn.textContent = "Show the prompt used (+ design rationale)"; return; }
        var pb = document.createElement("div");
        pb.className = "prompt-box";
        var note =
          "PROMPT DESIGN NOTE: The following techniques are used in this project:\n" +
          "- System role + rule list (guided generation): non-judgmental language, no-diagnosis rule, point attribution.\n" +
          "- Daily reflection: few-shot (2 examples: a normal day + a hard day) + structured data (JSON) + verification step.\n" +
          "- Weekly summary: step-by-step (STEP 1-4) structured prompting + verification step.\n" +
          "- Delimiters: KOMUT/DATA/EXAMPLE/VERIFY separation.\n" +
          "- Notification coach (break suggestion): system rules + 2 few-shot examples + JSON output (" +
          "title/body/breakOffer/points) producing dynamic, guilt-free notifications based on the user's context (hour, overshoot, streak)." +
          "\n- Temperature: reflection 0.5, chat 0.7, notification 0.8.\n" +
          "\n- Only an anonymous summary of the data is sent; it contains no username or identity.\n\n" +
          res.prompt;
        pb.textContent = note;
        wrap.appendChild(pb);
        btn.textContent = "Hide prompt";
      });
      wrap.appendChild(btn);
    }).catch(function (err) {
      out.className = "ai-output error";
      out.textContent = "Unexpected error: " + err.message;
    });
  }

  $("btnDailyAI").addEventListener("click", function () { runAI("daily"); });
  $("btnWeeklyAI").addEventListener("click", function () { runAI("weekly"); });

  // ---------- modal ----------
  function openModal(innerHTML) {
    var root = $("modalRoot");
    root.innerHTML = "<div class='modal-backdrop'></div><div class='modal'>" + innerHTML + "</div>";
    root.classList.add("open");
    root.querySelector(".modal-backdrop").addEventListener("click", closeModal);
  }

  function closeModal() {
    var root = $("modalRoot");
    root.classList.remove("open");
    root.innerHTML = "";
  }

  function providerLabel() {
    return state.ai.provider === "gemini" ? "Google Gemini" : "OpenAI";
  }

  // ---------- Settings ----------
  function openSettings() {
    openModal(
      "<h3>Settings</h3>" +
      "<div class='field'><label>Live AI connection</label><label class='switch-line'>" +
      "<input type='checkbox' id='setLive'" + (state.ai.live ? " checked" : "") + "> <span>Use a real model with an API key</span></label></div>" +
      "<div class='field'><label>Provider (AI vendor)</label>" +
      "<select id='setProvider'>" +
      "<option value='openai'" + (state.ai.provider !== "gemini" ? " selected" : "") + ">OpenAI</option>" +
      "<option value='gemini'" + (state.ai.provider === "gemini" ? " selected" : "") + ">Google Gemini</option>" +
      "</select></div>" +
      "<div class='field'><label>API base URL</label><input id='setBase' value='" + esc(state.ai.baseUrl) + "'></div>" +
      "<div class='field'><label>Model (type a fine-tuned model name here for Gemini)</label><input id='setModel' value='" + esc(state.ai.model) + "'></div>" +
      "<div class='field'><label>API key (stored only on this device)</label><input id='setKey' type='password' value='" + esc(state.ai.apiKey) + "' placeholder='sk-... or AIza...'></div>" +
      "<div class='row'>" +
      "<button class='btn btn-primary' id='setSave'>Save</button>" +
      "<button class='btn' id='setCancel'>Cancel</button>" +
      "</div>" +
      "<div class='row' style='margin-top:16px'>" +
      "<button class='btn btn-danger-ghost' id='btnReset2'>Reset demo</button>" +
      "</div>" +
      "<div class='row' style='margin-top:16px'>" +
      "<button class='btn btn-primary' id='btnExport'>Download my data (JSON)</button>" +
      "</div>" +
      "<div class='row' style='margin-top:8px'>" +
      "<button class='btn btn-danger-ghost' id='btnRevokeConsent'>Withdraw consent</button>" +
      "</div>" +
      "<div class='row' style='margin-top:8px'>" +
      "<button class='btn btn-danger-ghost' id='btnWipeData'>Delete my data</button>" +
      "</div>" +
      "<p class='muted small' style='margin-top:12px'>Under KVKK arts. 7, 10 and 11: you may withdraw your explicit consent at any time, download your data as JSON (right of access), or have it permanently deleted (right of erasure). \"Reset demo\" clears the demo data; \"Delete my data\" permanently removes all of your data from this device, including explicit consent, and locks the app.</p>" +
      "<p class='muted small' style='margin-top:8px'>These are general-purpose language models; project-specific coach behavior is provided through the system prompt (fine-tuning equivalent). Template generation works while the live connection is off. Data privacy: records stay only in this browser; only an anonymous session summary and (in chat) the last messages go to the API. For Gemini, the model URL and key are set automatically for the selected provider; you can use a custom or fine-tuned model by changing the model name.</p>"
    );
    $("setSave").addEventListener("click", function () {
      state.ai.live = $("setLive").checked;
      state.ai.provider = $("setProvider").value;
      state.ai.baseUrl = $("setBase").value.trim() || "https://api.openai.com/v1";
      state.ai.model = $("setModel").value.trim() || "gpt-4o-mini";
      state.ai.apiKey = $("setKey").value.trim();
      save();
      closeModal();
      renderAIStatus();
    });
    $("setProvider").addEventListener("change", function () {
      var p = $("setProvider").value;
      if (p === "gemini") {
        if (!$("setBase").value || $("setBase").value.indexOf("generativelanguage") === -1) $("setBase").value = "https://generativelanguage.googleapis.com/v1beta";
        if ($("setModel").value.indexOf("gemini") === -1) $("setModel").value = "gemini-3.6-flash";
      } else {
        if ($("setBase").value.indexOf("generativelanguage") !== -1) $("setBase").value = "https://api.openai.com/v1";
        if ($("setModel").value.indexOf("gemini") !== -1) $("setModel").value = "gpt-4o-mini";
      }
    });
    $("setCancel").addEventListener("click", closeModal);
    $("btnReset2").addEventListener("click", confirmReset);
    $("btnExport").addEventListener("click", exportData);
    $("btnRevokeConsent").addEventListener("click", confirmRevokeConsent);
    $("btnWipeData").addEventListener("click", confirmWipeData);
  }

  function exportData() {
    closeModal();
    try {
      var blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" });
      var url = URL.createObjectURL(blob);
      var a = document.createElement("a");
      a.href = url;
      a.download = "sozumsoz-my-data.json";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(function () { try { URL.revokeObjectURL(url); } catch (e) { /* noop */ } }, 1000);
    } catch (e) {
      openModal(
        "<h3>Download my data</h3>" +
        "<p>Your browser does not support file downloads in this environment. Your data is still on this device; you can permanently delete it at any time via 'Settings → Delete my data'.</p>" +
        "<div class='row'><button class='btn btn-primary' id='exportOk'>OK</button></div>"
      );
      $("exportOk").addEventListener("click", closeModal);
    }
  }

  function confirmRevokeConsent() {
    closeModal();
    openModal(
      "<h3>Withdraw consent</h3>" +
      "<p>Under KVKK art. 7, you are withdrawing your explicit consent. Once consent is withdrawn, the SÖZÜM SÖZ app is locked and your data is no longer processed for these purposes. Your existing data stays on the device; if you wish, you can permanently remove it with 'Delete my data'.</p>" +
      "<div class='row'>" +
      "<button class='btn btn-danger' id='revokeYes'>Yes, withdraw my consent</button>" +
      "<button class='btn' id='revokeNo'>Cancel</button>" +
      "</div>"
    );
    $("revokeYes").addEventListener("click", function () {
      state.consent = false;
      save();
      closeModal();
      renderHome();
    });
    $("revokeNo").addEventListener("click", closeModal);
  }

  function confirmWipeData() {
    closeModal();
    openModal(
      "<h3>Delete my data</h3>" +
      "<p>You are exercising your right of erasure under KVKK art. 11. All of your data, including explicit consent, will be <b>permanently deleted</b> from this device, the SÖZÜM SÖZ app will be locked, and your consent will be requested again on the next launch. This action cannot be undone. Are you sure?</p>" +
      "<div class='row'>" +
      "<button class='btn btn-danger' id='wipeYes'>Yes, delete my data</button>" +
      "<button class='btn' id='wipeNo'>Cancel</button>" +
      "</div>"
    );
    $("wipeYes").addEventListener("click", function () {
      try { localStorage.removeItem(STORE_KEY); } catch (e) { /* noop */ }
      location.reload();
    });
    $("wipeNo").addEventListener("click", closeModal);
  }

  function confirmReset() {
    closeModal();
    openModal(
      "<h3>Reset demo</h3>" +
      "<p>All points, promises, and settings data will be erased. Are you sure?</p>" +
      "<div class='row'>" +
      "<button class='btn btn-danger' id='resetYes'>Yes, reset</button>" +
      "<button class='btn' id='resetNo'>Cancel</button>" +
      "</div>"
    );
    $("resetYes").addEventListener("click", function () {
      try { localStorage.removeItem(STORE_KEY); } catch (e) { /* noop */ }
      location.reload();
    });
    $("resetNo").addEventListener("click", closeModal);
  }

  // ---------- intro step ----------
  function showIntro() {
    if (state.seenIntro) return;
    openModal(
      "<h3>Welcome to SÖZÜM SÖZ</h3>" +
      "<p>Digital dependence and digital well-being hackathon prototype. It works in 4 steps:</p>" +
      "<p>1) <b>Make a time promise:</b> When you enter an app, state how many minutes you commit to.<br>" +
      "2) <b>Keep your promise:</b> Close within the time for +3 points; if you exceed the time or immediately jump to another app you get -5 points and a warning.<br>" +
      "3) <b>Break suggestions:</b> The AI coach suggests small breaks like drinking water or resting your eyes when you exceed the time; you earn a few points by completing the break.<br>" +
      "4) <b>Earn and reflect:</b> Streak bonuses, the promise of the day, the Yeşilay reward catalog, a monthly draw, and the AI reflection coach support you.</p>" +
      "<p class='muted small'>While the fast demo is on, 1 second counts as ~1 minute, so you can test the whole flow in seconds.</p>" +
      "<div class='row'><button class='btn btn-primary btn-lg' id='introOk'>Got it, let's start</button></div>"
    );
    $("introOk").addEventListener("click", function () {
      state.seenIntro = true;
      save();
      closeModal();
    });
  }

  // ---------- misc ----------
  $("btnSettings").addEventListener("click", openSettings);
  $("btnReset").addEventListener("click", confirmReset);
  $("speedToggle").addEventListener("change", function () {
    state.speedFast = $("speedToggle").checked;
    save();
  });

  // ---------- weekly score emoji (demo) ----------
  document.querySelectorAll("#moodRow .btn").forEach(function (b) {
    b.addEventListener("click", function () {
      var m = b.getAttribute("data-mood");
      state.weeklyDemo = m === "auto" ? null : m;
      save();
      renderHeader();
    });
  });

  // ---------- CHAT (multi-turn AI coach) ----------
  function appendChat(role, text, opts) {
    var log = $("chatLog");
    var empty = log.querySelector(".chat-empty");
    if (empty) empty.remove();
    var el = document.createElement("div");
    el.className = "chat-msg " + (role === "user" ? "user" : "assistant");
    if (role === "user") {
      el.innerHTML = "<div>" + esc(text).split("\n").join("<br>") + "</div>";
    } else if (opts && opts.busy) {
      el.innerHTML = "<span>Coach is thinking</span><span class='ai-dots'></span>";
      el.classList.add("chat-busy");
    } else {
      var badge = document.createElement("div");
      badge.className = "ai-badge";
      badge.textContent = "AI";
      el.appendChild(badge);
      var body = document.createElement("div");
      body.style.whiteSpace = "pre-wrap";
      el.appendChild(body);
      typeText(body, text, function () {
        var stamp = document.createElement("div");
        stamp.className = "ai-stamp";
        stamp.textContent = AI_STAMP;
        el.appendChild(stamp);
        if (opts && opts.note) {
          var n = document.createElement("div");
          n.className = "chat-note";
          n.textContent = opts.note;
          el.appendChild(n);
        }
      });
    }
    log.appendChild(el);
    log.scrollTop = log.scrollHeight;
    return el;
  }

  var chatBusy = false;

  function doSendChat() {
    var input = $("chatInput");
    var text = (input.value || "").trim();
    if (!text || chatBusy) return;
    chatBusy = true;
    var sendBtn = $("chatSend");
    sendBtn.disabled = true;
    input.value = "";
    appendChat("user", text, {});
    state.chatHistory.push({ role: "user", content: text, ts: Date.now() });
    state.chatHistory = state.chatHistory.slice(-40);
    save();
    var busyEl = appendChat("assistant", "Coach is thinking...", { busy: true });
    AI.chat(state.ai, sessionsSince(7), state.chatHistory).then(function (res) {
      var note = res.source === "live" ? "Live model response"
        : res.source === "live-error" ? "Live call failed, showing template: " + res.error
        : "Template response (live connection off)";
      state.chatHistory.push({ role: "assistant", content: res.text, ts: Date.now() });
      state.chatHistory = state.chatHistory.slice(-40);
      save();
      if (busyEl.parentNode) busyEl.parentNode.removeChild(busyEl);
      appendChat("assistant", res.text, { note: note });
      chatBusy = false;
      sendBtn.disabled = false;
    }).catch(function (err) {
      if (busyEl.parentNode) busyEl.parentNode.removeChild(busyEl);
      appendChat("assistant", "Unexpected error: " + err.message, {});
      chatBusy = false;
      sendBtn.disabled = false;
    });
  }

  $("chatSend").addEventListener("click", doSendChat);
  $("chatInput").addEventListener("keydown", function (e) {
    if (e.key === "Enter") doSendChat();
  });
  document.querySelectorAll(".chip").forEach(function (c) {
    c.addEventListener("click", function () {
      $("chatInput").value = c.getAttribute("data-q");
      doSendChat();
    });
  });

  function init() {
    load();
    ensureWeeklyChallenges();
    bootApp();
  }

  function bootApp() {
    appBooted = true;
    var bm = document.querySelector(".topbar .brand-mark");
    if (bm && SOZ_LOGO) {
      bm.innerHTML = "<img class='brand-mark-img' src='" + SOZ_LOGO + "' alt='SÖZÜM SÖZ'>";
    }
    renderHeader();
    setTab("phone");
    renderHome();
    renderFeed();
    renderStats();
    renderAIStatus();
    setTimeout(showIntro, 350);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();